version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka
    ports:
        - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.136
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  app:
    build: 
      context: .
      dockerfile: Dockerfile  
    environment:
      KAFKA_SERVER_CONNECT: kafka:9092
    volumes:
      - ..:/app:cached
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"  